### ISSUE TITLE
Cinematic Bars fail to load in

### ISSUE THREAD

**Issue by myffs** [LilDrippyMyFnf/VS-STUPID-UPDATE#11]
### Describe your bug here.

So you know in UnNatural Substance, their's cinematic bars that cover the screen? Well i downloaded a build and i played UnNatural Substance. Then i noticed that the cinematic bars were gone. I even reloaded the .exe file a few times. And it still wasn't showing.

Just Download a build and play "UnNatural Substance". I wish i could show a screenshot but i can't cuz my screenshot thing is broken. If you encounter the issue, screenshot it ( if you fixed it ) and tell me what i need to fix ( You can commit it yourself if your a contrubitor ).

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just updated the cinematic bars since i saw that it was missing, it was still missing the texture when i updated t

**Comment by moxie-coder** [comment]
please stop using the invalid label for bugs, as it's usually made for issues themself that aren't valid, not the bugs

**Comment by myffs** [comment]
ok sorry

**Comment by moxie-coder** [comment]
it's okay

**Comment by myffs** [comment]
anyway backto the overall issue

**Comment by myffs** [comment]
can you try to fix the cinematic bar plz?

**Comment by moxie-coder** [comment]
okay
