### ISSUE TITLE
Credits menu colors only default to a "FFFFFF" ( white ) color

### ISSUE THREAD

**Issue by myffs** [LilDrippyMyFnf/VS-STUPID-UPDATE#13]
### Describe your bug here.

So in the credits menu, the background color is displaying a "white" color instead of defaulting to the color codes in the CreditsState.hx 

example: `FFC0CB < FFFFFF`

Basically, if you type a color code in like `FFC0CB`, the game will `default` that color code to `FFFFFF`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just noticed it.

**Comment by moxie-coder** [comment]
it does this on regular psych too, idk why

**Comment by moxie-coder** [comment]
I'll just wait for shadowmario to push a fix for now, since it's not that important of an issue tbh
