### ISSUE TITLE
Lag spikes when loading up the game for the first time

### ISSUE THREAD

**Issue by myffs** [LilDrippyMyFnf/VS-STUPID-UPDATE#15]
### Describe your bug here.

So every time i download a new build of the mod, lag spikes occur ( my discord app closes when i load a song, the game closes crashes alot ).

Issue with my PC? or some dlls need installing?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i just download builds and play test them

**Comment by moxie-coder** [comment]
issue with your pc, not the game

**Comment by myffs** [comment]
xd

**Comment by moxie-coder** [comment]
lol
