### ISSUE TITLE
Cinematic bars are BACK, but the notes are hard to see

### ISSUE THREAD

**Issue by JoseDev1664** [LilDrippyMyFnf/VS-STUPID-UPDATE#16]
### Describe your bug here.

Cinematic bars work now

But...the notes get half cut off

### Command Prompt/Terminal logs (if existing)

```bash
...
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by myffs** [comment]
it's like i've seen that in the CURRENT BUILDS
