### ISSUE TITLE
PATMICK's png, won't load in

### ISSUE THREAD

**Issue by myffs** [LilDrippyMyFnf/VS-STUPID-UPDATE#3]
### Describe your bug here.

when i try to load in PATMICK's json file, his png doesn't show but his json and xml are fine and his png is their too. is there any way this can be fixed?

### Command Prompt/Terminal logs (if existing)

```bash
crash message when loaded: Null object reference
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not really, i only added PATMICK's file stuff in

**Comment by moxie-coder** [comment]
you probably didn't put in the right png name in the character json

**Comment by myffs** [comment]
hmmm

**Comment by moxie-coder** [comment]
wait nvm I can look why it's crashing

**Comment by moxie-coder** [comment]
it works fine for me @LilDrippyMyFnf

**Comment by myffs** [comment]
it doesnt for me

**Comment by myffs** [comment]
send me the right and fixed one
 

pls

**Comment by moxie-coder** [comment]
alr

**Comment by myffs** [comment]
mediafile

**Comment by myffs** [comment]
i guess

**Comment by myffs** [comment]
what about the stupid's week issue too

**Comment by moxie-coder** [comment]
idk, might be an issue with your pc

**Comment by myffs** [comment]
ok, thanks for letting me know

**Comment by moxie-coder** [comment]
you're welcome
