### ISSUE TITLE
Why is week 3 not playable?

### ISSUE THREAD

**Issue by JoseDev1664** [LilDrippyMyFnf/VS-STUPID-UPDATE#6]
### Describe your bug here.

When I try to load in a song in week 3 I can't and then it shows a error.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by myffs** [comment]
I haven't worked on the songs + data yet

**Comment by JoseDev1664** [comment]
Oh ok
