### ISSUE TITLE
Finish chart for static hit

### ISSUE THREAD

**Issue by JoseDev1664** [LilDrippyMyFnf/VS-STUPID-UPDATE#7]
### What feature do you want to get added on the **base** engine?

Finish the chart its like 90% completed

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by myffs** [comment]
HOLY SHIT. i'm going to finish it, god damn

**Comment by JoseDev1664** [comment]
OK sorry :((
