### ISSUE TITLE
Why are some of the chatacters sprites not loaded in / show?

### ISSUE THREAD

**Issue by JoseDev1664** [LilDrippyMyFnf/VS-STUPID-UPDATE#8]
### What is your question?

Besides StupidNor and StupidMads spritesheet, every character has a missing sprite, is there a issue with the .json files or just lack of artist?

**Comment by myffs** [comment]
Well, its both, We have lack of artist and musicians so yeah if you have any ppl to help dm me. and sometimes the sprites don't load in and idk why it does that

**Comment by JoseDev1664** [comment]
Aww man, I don't have anyone I can help out

**Comment by myffs** [comment]
ok
