### ISSUE TITLE
Why the FUCK is warnings chart not even charted correctly

### ISSUE THREAD

**Issue by JoseDev1664** [LilDrippyMyFnf/VS-STUPID-UPDATE#9]
### Describe your bug here.

Bro warnings chart doesn't even match the song like wtf💀

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, but I think the chart needs to👾

**Comment by myffs** [comment]
Oh, its cuz i got lazy to fix the chart and thank you for noticing that for the 1000000000000000th time, cuz so many people have seen that 💀

**Comment by JoseDev1664** [comment]
Wow, why can't you just fix the chart

**Comment by myffs** [comment]
i dont have much time cuz of school
